[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gait"
version = "0.1.2"
description = "Review your code changes in a git repository using an LLM"
authors = [{ name = "Can Tașlıçukur", email = "can.taslicukur@ozu.edu.tr" }]
readme = "README.md"
license = "Apache-2.0"
dependencies = ["gitpython>=3.1.44", "openai>=1.64.0", "typer>=0.15.1"]
requires-python = ">=3.13"

[project.urls]
Repository = "https://github.com/can-taslicukur/gait"

[project.scripts]
gait = "gait.main:app"

[dependency-groups]
dev = ["pytest>=8.3.4", "pytest-snapshot>=0.9.0"]
lint = ["ruff>=0.9.7"]

[tool.ruff]
line-length = 100
lint.select = ["E", "W", "F", "I", "C", "B"]
